# Generated by Django 5.0.2 on 2024-03-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categorie_rename_carts_cart_rename_orders_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Categories',
        ),
        migrations.RemoveField(
            model_name='carts_item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
