# Generated by Django 5.0.2 on 2024-03-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_categorie_categories_remove_carts_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_value',
            field=models.FloatField(default=''),
        ),
    ]
