# Generated by Django 5.0.2 on 2024-03-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_discount_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
    ]
