# Generated by Django 5.0.2 on 2024-03-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_categories_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderLine',
        ),
    ]
